steps:
  # Deploy all Firebase services (Firestore rules/indexes, Functions, and Hosting)
  # Uses Application Default Credentials (ADC) from Cloud Build service account
  - name: 'us-docker.pkg.dev/firebase-cli/us/firebase'
    args:
      - 'deploy'
      - '--project=respondentpro-xyz'
      - '--non-interactive'
  
  # Create or update Cloud Scheduler jobs for scheduled endpoints
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get the function URL (Cloud Function endpoint)
        FUNCTION_URL="https://us-central1-respondentpro-xyz.cloudfunctions.net/respondentpro"
        
        # Create or update cache refresh job (runs daily at 6:00 AM)
        gcloud scheduler jobs create http scheduled-cache-refresh \
          --project=respondentpro-xyz \
          --location=us-central1 \
          --schedule="0 6 * * *" \
          --uri="$${FUNCTION_URL}/scheduled/cache-refresh" \
          --http-method=GET \
          --time-zone="America/Chicago" \
          || gcloud scheduler jobs update http scheduled-cache-refresh \
          --project=respondentpro-xyz \
          --location=us-central1 \
          --schedule="0 6 * * *" \
          --uri="$${FUNCTION_URL}/scheduled/cache-refresh" \
          --http-method=GET \
          --time-zone="America/Chicago"
        
        # Create or update session keepalive job (runs every 8 hours)
        gcloud scheduler jobs create http scheduled-session-keepalive \
          --project=respondentpro-xyz \
          --location=us-central1 \
          --schedule="0 */8 * * *" \
          --uri="$${FUNCTION_URL}/scheduled/session-keepalive" \
          --http-method=GET \
          --time-zone="America/Chicago" \
          || gcloud scheduler jobs update http scheduled-session-keepalive \
          --project=respondentpro-xyz \
          --location=us-central1 \
          --schedule="0 */8 * * *" \
          --uri="$${FUNCTION_URL}/scheduled/session-keepalive" \
          --http-method=GET \
          --time-zone="America/Chicago"
        
        # Create or update notifications job (runs every Friday at 9:00 AM)
        gcloud scheduler jobs create http scheduled-notifications \
          --project=respondentpro-xyz \
          --location=us-central1 \
          --schedule="0 9 * * 5" \
          --uri="$${FUNCTION_URL}/scheduled/notifications" \
          --http-method=GET \
          --time-zone="America/Chicago" \
          || gcloud scheduler jobs update http scheduled-notifications \
          --project=respondentpro-xyz \
          --location=us-central1 \
          --schedule="0 9 * * 5" \
          --uri="$${FUNCTION_URL}/scheduled/notifications" \
          --http-method=GET \
          --time-zone="America/Chicago"

# No substitution variables needed - uses Cloud Build service account credentials
# Make sure the Cloud Build service account has roles/firebase.admin permission

# Build timeout (optional, adjust as needed)
timeout: '1200s'

# Build options - required when service_account is specified
options:
  logging: CLOUD_LOGGING_ONLY
